### ISSUE TITLE
Recover from failure to install Raft snapshot

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/atomix#15]
**Is your feature request related to a problem? Please describe.**

Following #14, it would be good to recover from a bad snapshot by removing it and fetching a new one from the leader, for example.

**Describe the solution you'd like**

When a snapshot fails to be installed on a node, it should be discarded, and the node should be able to recover from the others.

**Comment by npepinpe** [comment]
Opened on Atomix side: https://github.com/atomix/atomix/issues/1038

**Comment by ChrisKujawa** [comment]
I saw this quite often now.

```
06:28:32.733 [] [raft-server-raft-atomix-partition-1-state] ERROR io.atomix.protocols.raft.impl.RaftServiceManager - RaftServer{raft-atomix-partition-1} - Expected to read snapshot, but caught a non recoverable error; blocking thread to avoid applying further entries and creating inconsistencies
java.lang.IllegalStateException: cannot read from unlocked snapshot descriptor
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508) ~[guava-28.0-jre.jar:?]
        at io.atomix.protocols.raft.storage.snapshot.Snapshot.openReader(Snapshot.java:154) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.storage.snapshot.FileSnapshot.openReader(FileSnapshot.java:65) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.install(RaftServiceManager.java:499) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.protocols.raft.impl.RaftServiceManager.lambda$apply$12(RaftServiceManager.java:422) ~[atomix-raft-3.2.0-alpha2.jar:?]
        at io.atomix.utils.concurrent.SingleThreadContext$1.lambda$execute$0(SingleThreadContext.java:53) ~[atomix-utils-3.2.0-alpha2.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_212]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by npepinpe** [comment]
I think this is another corrupted snapshot, as afaik Atomix doesn't try to install unlocked snapshots, it just ignores them, but I'll verify that.

EDIT: from what I understand, Atomix wouldn't attempt to install a snapshot that is "unlocked" (i.e. incomplete), as it only loads completed snapshot in its in-memory snapshot store. Could be a bug there, or again the same bug as before where we get messed up snapshots.

**Comment by npepinpe** [comment]
For posterity, leaving links to the [corrupted snapshot](https://drive.google.com/file/d/1GYPiw-mj5LPK-9DtRXEUmXNbDQWA6xzj) and a [sample normal one](https://drive.google.com/file/d/1mOIWYuMr0xxIFtYY9p6H4OPNs3V3Ax1M)

**Comment by menski** [comment]
@npepinpe the "corrupted snapshot" link gives we access denied error

**Comment by npepinpe** [comment]
Not really relevant anymore, snapshots are completely handled on the Zeebe side
