### ISSUE TITLE
Events not always gossipped to all nodes

### ISSUE THREAD

**Issue by npepinpe** [zeebe-io/atomix#16]
With a gossip fan out smaller than the cluster size, it's possible that some gossip updates are not propagated to the whole cluster if nodes keep picking the same nodes over and over.

During our test we get the following gossip pattern:

`zeebe-0`:
```
13:00:29.630 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}}
13:00:29.634 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 0 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}}
```

`zeebe-1`:
```
13:00:29.751 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 1 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}}
13:00:29.751 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 1 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}}
```

`zeebe-2`:
```
13:00:29.924 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 2 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}}
13:00:29.927 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 2 - Gossipping updates [Member{id=4, address=zeebe-4.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":4,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-4.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"3":false,"4":false,"5":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846567, state=ALIVE, incarnationNumber=1561033846573}] to Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}}
```

`zeebe-3`:
```
```

`zeebe-4`:
```
13:00:29.820 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}, version=3.2.0-alpha1, timestamp=1561033847627, state=ALIVE, incarnationNumber=1561033847630}] to Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}}
13:00:33.820 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846670, state=ALIVE, incarnationNumber=1561033846672}] to Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}}
13:00:33.822 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=2, address=zeebe-2.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":2,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-2.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"2":false,"3":true,"6":true,"7":false,"8":false}}}, version=3.2.0-alpha1, timestamp=1561033846670, state=ALIVE, incarnationNumber=1561033846672}] to Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}}
13:00:34.820 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}, version=3.2.0-alpha1, timestamp=1561033846747, state=ALIVE, incarnationNumber=1561033846750}] to Member{id=0, address=zeebe-0.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":0,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-0.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":false,"4":true,"5":true,"6":false}}}}
13:00:34.821 [] [atomix-cluster-heartbeat-sender] TRACE io.atomix.cluster.protocol.SwimMembershipProtocol - 4 - Gossipping updates [Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}, version=3.2.0-alpha1, timestamp=1561033846747, state=ALIVE, incarnationNumber=1561033846750}] to Member{id=1, address=zeebe-1.zeebe.npepinpe.svc.cluster.local:26502, properties={brokerInfo={"nodeId":1,"partitionsCount":8,"clusterSize":5,"replicationFactor":3,"addresses":{"command":"zeebe-1.zeebe.npepinpe.svc.cluster.local:26501"},"partitionRoles":{"1":true,"2":true,"5":false,"6":false,"7":true}}}}
```

**Comment by ChrisKujawa** [comment]
Oha, `zeebe-3` is the best :see_no_evil: Do you know what is the default spread count ?

**Comment by deepthidevaki** [comment]
> Oha, `zeebe-3` is the best see_no_evil Do you know what is the default spread count ?

2

**Comment by ChrisKujawa** [comment]
Can we configure this?

**Comment by npepinpe** [comment]
Yes it's an Atomix config setting, but I think the issue here is that the node who triggered the update is picked quite often (unnecessarily), don't think it's necessary to fan out to all nodes in the cluster.

**Comment by menski** [comment]
Let's prefer a solution where we keep the gossip fan out small, otherwise we might lose the advantages of gossip in a bigger cluster.

**Comment by npepinpe** [comment]
I'd like to propose we work on fixing this again. I pushed a branch with a horrible test, but it highlights the problem - if you run it in a loop until failure, it will eventually fail as one of the nodes is missing some updates.

https://github.com/zeebe-io/atomix/commit/c57a216fd9b8d771997b5decde974237011b5d71

Basically, eventually you will see an error like:

```
java.lang.AssertionError: Unexpected event null

	at io.atomix.cluster.protocol.SwimProtocolTest.checkEvents(SwimProtocolTest.java:337)
	at io.atomix.cluster.protocol.SwimProtocolTest.shouldEventuallyPropagateUpdates(SwimProtocolTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

Which means we were expecting some event (e.g. member3 rejoining) but that node never received anything.

**Comment by npepinpe** [comment]
Cross posting from zeebe:

> After discussion, we decided to go with the following solution:
>
> - Every node keeps a queue of syncNodes
> - Initially, that queue contains all known nodes, shuffled
> - Every X seconds (configurable) +- some randomized offset, poll the queue, and sync with that node
> - If the list is empty, recreate it as a shuffled copy of the list of known nodes
> 
> So essentially, after some time, every node should have a consistent view of the cluster. With a high enough X, we shouldn't see too much additional traffic, but we'll be sure to run a benchmark.
